Robots
uncerso/code-graveyard pull request #2
Opened 2017-11-12 21:15 UTC by uncerso

2017-12-01 13:09 UTC, yurii-litvinov requested changes

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/robots.cpp
> +#define NOT_A_COLOR 2
А чего не `const int notAColor = 2;`? Не на C же программируете :)

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/robots.hpp
> +	bool dfs(uint, bool, std::vector<uint> ) noexcept;
Лучше имена параметров всё-таки писать, так всплывающие подсказки в IDEшке будут более вменяемыми

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/robots.cpp
> +bool Robots::dfs(uint pos, bool color, vector<uint> colors) noexcept {
А зачем colors по значению передаётся?

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/robots.cpp
> +	for (auto &v : graph[pos]) {
Оно же uint, зачем оно по ссылке? И главное, почему не const? :)

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/robots.cpp
> +	if (dfs(0, false, colors) && !(amountOfRobots & 1)) return true;  //Odd loop with even amount of robots
Поскольку все роботы могут телепортироваться одновременно, то нам даже не интересно, чётное ли их количество, нам важно только, что их больше 1 (или 0)

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/robots.cpp
> +	return !(1 & (cntColor1 | cntColor2)); //ItObvious
Ну и тут тоже, три робота могут одновременно телепортироваться в одну вершину и убить себя, чётность не очень важна

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/source.cpp
> +	// cout << (robots.solve() == ans);
Лучше без закомментированного кода

2017-12-01 13:09 UTC, yurii-litvinov commented on robots/source.cpp
> +Robots loadToSample(string nameOfFile) noexcept {
Тут тоже лучше по константной ссылке принимать

2017-12-01 14:40 UTC, uncerso commented on robots/robots.cpp
> +bool Robots::dfs(uint pos, bool color, vector<uint> colors) noexcept {
Упс.

2017-12-01 14:40 UTC, uncerso commented on robots/robots.cpp
> +	if (dfs(0, false, colors) && !(amountOfRobots & 1)) return true;  //Odd loop with even amount of robots
Вы это объяснили уже после того, как всё работало. Ну и вы разрешили всё так и оставить.

2017-12-01 14:44 UTC, uncerso commented on robots/robots.cpp
> +#define NOT_A_COLOR 2
Почему бы и не макрос. Зачем быть глобальной константе во время исполнения? (Хотя компиляторы весьма умные)

2017-12-02 07:55 UTC, yurii-litvinov commented on robots/robots.cpp
> +#define NOT_A_COLOR 2
Да, константу скорее всего компилятор "протянет" и во время выполнения от неё ничего не останется. Макросы многими стайлгайдами запрещены, потому что практически всё, что можно сделать макросами, можно сделать константами и шаблонами, но типобезопасно, с адекватной привязкой и без странных ошибок

2017-12-02 07:55 UTC, yurii-litvinov commented on robots/robots.cpp
> +	if (dfs(0, false, colors) && !(amountOfRobots & 1)) return true;  //Odd loop with even amount of robots
Ну раз я разрешил, то ладно :)

2017-12-02 08:15 UTC, yurii-litvinov commented
Ужасные комментарии к коммитам и тот факт, что оно не собирается, намекает на то, что Вы решили поправить код прямо на гитхабе, но не настроили CI :)

2017-12-03 13:19 UTC, yurii-litvinov approved these changes
Ок, зачтена.

2017-12-03 13:19 UTC, yurii-litvinov commented on robots/robots.cpp
> +const int notAColor(2);
Я б ещё пустых строк тут куда-нить вставил (между include и const точно просится, между const и using --- тоже было бы неплохо). Но дело вкуса.

2017-12-26 12:24 UTC, merged