It may be works
uncerso/code-graveyard pull request #6
Opened 2018-02-17 17:23 UTC by uncerso

2018-02-18 08:57 UTC, yurii-litvinov requested changes
Папки bin и obj выкладывать не нужно, это результаты сборки. Надо удалить лишнее, поправить стайлгайд и мелкие замечания.

2018-02-18 08:57 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    if (n<2I) then 1I else n*factorial(n-1I)
В F# бинарные операторы тоже выделяются пробелами

2018-02-18 08:57 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +let rec fib n mn mx : bigint =
mn, mx --- не очень говорящие имена переменных. Кроме того, fib, поскольку у неё такое некрасивое имя, лучше сделать вложенной функцией в fibonacci (я про это ещё не рассказывал, конечно)

2018-02-18 08:57 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    List.foldBack (fun el acc -> List.append acc [el;]) ls []
В F# списки немутабельны, поэтому append будет работать за линейное время (ей надо скопировать весь первый список). А вот операция добавления в голову работает за константное время, так что тут можно было применить тот же приём, что и в Фибоначчи --- отдельный параметр для хранения промежуточного результата.

2018-02-18 08:57 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    List.init m (fun index -> 2I**(n+index))
Операция возведения в степень довольно дорогая, тут её можно было выполнить только один раз

2018-02-18 08:57 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    printfn "%s\n" <| factorial(read()).ToString()
можно было `printfn "%d\n"`, и тогда без `ToString()`. Впрочем, я, как обычно, про это не рассказывал :)

2018-02-18 10:35 UTC, uncerso commented on FirstSteps/FirstSteps/Program.fs
> +    printfn "%s\n" <| factorial(read()).ToString()
Оно точно bigint выводит? А то я попроблвал, что-то было не то. Хотя мб я напутал что.

2018-02-18 10:39 UTC, uncerso commented on FirstSteps/FirstSteps/Program.fs
> +    List.init m (fun index -> 2I**(n+index))
Прям дорогая? log(n) для 2^n не так уж и много, учитывая, что скорость тут не нужна. Или тут ** сделано за линию?

2018-02-18 10:42 UTC, uncerso commented on FirstSteps/FirstSteps/Program.fs
> +    List.foldBack (fun el acc -> List.append acc [el;]) ls []
Т.е. Если делать список.append(элемент) - O(n), а list(элемент).append(список) - O(1)? И даже mutable для списка не сделает в первом случае O(1)?

2018-02-18 11:38 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    printfn "%s\n" <| factorial(read()).ToString()
А, bigint надо не %d, а %A или %O (кстати, %O означает как раз "вызвать ToString(), а %A --- вызвать функцию any_to_string, которая если не перегружена для данного типа, тоже вызовет ToString())

2018-02-18 11:39 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    List.init m (fun index -> 2I**(n+index))
Я думаю, что за log(n), но тут-то можно за константу. Да, я сам всегда говорю, что излишняя оптимизация --- это плохо, но в данном случае это делает задачу немножко более интересной. Но вообще Вы правы, так что если не хотите это переделывать --- не надо, пробелы только поставьте

2018-02-18 11:41 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    List.foldBack (fun el acc -> List.append acc [el;]) ls []
Именно так. Я на паре расскажу, почему так. mutable сделает изменяемой ссылочную переменную, указывающую на список, но сам список так и будет немутабельным. То поведение, что Вы хотите, можно получить с помощью обычного дотнетовского System.Collections.Generic.List, но в первых домашкаах его использовать нельзя.

2018-02-19 16:39 UTC, yurii-litvinov approved these changes
Да, всё так, все зачтены

2018-02-19 16:39 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program.fs
> +    List.fold (fun acc el -> List.append [el;] acc) [] ls
Лучше el :: acc

2018-02-23 14:22 UTC, yurii-litvinov requested changes
Все, кроме второй, зачтены

2018-02-23 14:22 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program2.fs
> +    if (abs(x) < 10I) then abs(x) else (x % 10I) * productOfDigitsOfNumber(x / 10I)
Наверное, более идеологически правильно для F# было бы ставить пробел между именем функции и параметрами, даже если параметр всего один, и по возможности не ставить скобок

2018-02-23 14:22 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program2.fs
> +    max -1 (-List.fold (fun acc el -> if acc < 0 then acc elif pattern = el then -acc else (acc + 1)) 0 ls)
Лучше возвращать Option, чтобы если элемента в списке не нашлось, вызывающий был морально готов к этому и система типов подсказала бы, что надо рассмотреть этот случай

2018-02-23 14:22 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program2.fs
> +    max -1 (-List.fold (fun acc el -> if acc < 0 then acc elif pattern = el then -acc else (acc + 1)) 0 ls)
И не работает на таком тесте:
```
> findAndGetFirstIndexes [1; 2; 3] 1;;
val it : int = -1
```

2018-02-23 14:22 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program2.fs
> +        (a, b)
Не то чтобы хорошие имена переменных

2018-02-23 14:22 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program2.fs
> +    printfn "%A\n%A\nEnter your number from 0 to 9" <| [0..n-1] <| ls
Арифметические операторы выделяются пробелами, так что правильнее `n - 1`

2018-02-24 10:45 UTC, yurii-litvinov approved these changes
Ага, зачтена

2018-02-24 10:45 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program2.fs
> +    let acc1, acc2 = List.fold (fun (acc1, acc2) el -> if acc2 then (acc1, acc2) elif pattern = el then (acc1, true) else (acc1 + 1, false)) (0, false) ls
Жесть :) Но названия acc1 и acc2 мне не нравятся --- непонятно, кто из них кто и что за что отвечает.

2018-03-09 12:34 UTC, yurii-litvinov requested changes
Давайте первую задачу надо будет поправить (и заодно вынести тесты в отдельный проект), а остальные зачтены

2018-03-09 12:34 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program3.fs
> +    List.length (List.filter (fun el -> if ((el &&& 1) = 0) then true else false) ls)
`then true else false` не нужно :) И тут pipe forward смотрелся бы симпатичнее

2018-03-09 12:34 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program3.fs
> +    List.sum (List.map (fun el -> if ((el &&& 1) = 0) then 1 else 0) ls)
просто `(el + 1) % 2` было бы короче и даже более читабельно

2018-03-09 12:34 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program3.fs
> +let task1Tests =
Вообще, тесты лучше держать в отдельном проекте, они ведь не должны поставляться пользователю

2018-03-09 12:34 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program3.fs
> +    | Tip(x) -> printf "%d " x;
А вот тут точка с запятой не нужна. На самом деле и в строке выше лучше было бы записать не через точку с запятой, а на трёх отдельных строчках

2018-03-09 12:34 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program3.fs
> +    | Sum of Operator*Operator
Лучше выделять * пробелами

2018-03-09 12:34 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program3.fs
> +         for acc in 3UL..2UL..uint64 ((1I<<<64)-1I) do if (primeTest acc) then yield acc}
Тут тоже пробелов не хватает

2018-03-09 16:56 UTC, uncerso commented on FirstSteps/FirstSteps/Program3.fs
> +let task1Tests =
Эээ. Можно поподробнее?

2018-03-10 17:41 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program3.fs
> +let task1Tests =
Мм? Создаём отдельный проект (библиотеку), добавляем ссылку на сборку с решениями, пишем тесты. Примерно как здесь написано: https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md

2018-03-10 18:17 UTC, yurii-litvinov requested changes
Задачи 1 и 2 из 4-й домашки и задача 1 из 3-й зачтены, а задачу 3 из 4-й домашки надо поправить, и заодно всё-таки сделать юнит-тесты отдельно. Кстати, не хотите по отдельной ветке на каждую домашку?

2018-03-10 18:17 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +    reduction tm |> should equal ans
Гигантский мегатест --- это печально, разбейте, пожалуйста, на кучу маленьких

2018-03-10 18:17 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +type term =
Типы лучше именовать с заглавной

2018-03-10 18:17 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +    | Terms [] -> raise <| Errors("You can't use Terms []")
Можно сделать такое определение терма, при котором некорректные термы будут невозможны. Например, представлять терм не как список термов, а как аппликацию одного терма к другому

2018-03-10 18:17 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +| Lambda of list<string> * term
В лямбда-исчислении же не бывает функций от нескольких переменных :) То есть если хочется помучиться, то можно, но но просто Lambda of string * term было бы вполне норм

2018-03-10 18:17 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +        let rec replace a b tm=
Пробела не хватает :)

2018-03-10 18:17 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +            | [] -> apply (Terms ((replace a b t)::tail))
А тут не получится захвата переменной, если в подставляемый терм входит свободно связанная переменная? 
Например, `(\lambda x.(\lambda y.x y)) y`

2018-03-10 18:17 UTC, yurii-litvinov commented on hw.tex
> +Дальше нет смысла что-то делать, ведь ($\lambda$b.b b)($\lambda$b.b b) - расходящийся комбинатор.
Дефис вместо тире. Правильнее использовать `--` или `---`

2018-03-10 18:17 UTC, yurii-litvinov commented on hw.tex
> +$\lambda$z.$\lambda$y.z (K z) = $\lambda$z.z = I
Тут скобок не хватает. Это выражение надо читать как `\lambda$z.$\lambda$y.(z (K z))`, а на самом деле оно `\lambda$z.($\lambda$y.z) (K z)`.

2018-03-10 18:25 UTC, uncerso commented on FirstSteps/FirstSteps/Program4.fs
> +    reduction tm |> should equal ans
Что именно печально? Все составляющие этого теста были раньше, теперь всё вместе проверяется. Всё нормально. Вроде.

2018-03-10 18:27 UTC, uncerso commented on FirstSteps/FirstSteps/Program4.fs
> +    | Terms [] -> raise <| Errors("You can't use Terms []")
Но тогда 1ый элемент придётся проверять как-то особо. Да и вообще очень много доп проверок будет. Разбор случаев не есть хорошо. Это же можно не исправлять?

2018-03-10 18:31 UTC, uncerso commented on FirstSteps/FirstSteps/Program4.fs
> +| Lambda of list<string> * term
Это сделано ради адекватной записи термов. Иначе эта запись становится настолько гигантской, что прям адовый ужас. (это аналог  λx y z. .... Т.е. просто сокращение  λx.λy.λz....)

2018-03-10 18:31 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +    | Terms [] -> raise <| Errors("You can't use Terms []")
Так наоборот же, случаев будет ровно три --- переменная, абстракция и аппликация. А сейчас у Вас переменная, абстракция с нулём переменных, абстракция с одной переменной, ..., аппликация нуля термов (что нельзя), аппликация одного терма к одному, одного к двум и т.д.

2018-03-10 18:32 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +| Lambda of list<string> * term
Да, я понял, и это реально выглядит красиво, но несколько усложняет реализацию. Это можно не править

2018-03-10 18:34 UTC, uncerso commented on FirstSteps/FirstSteps/Program4.fs
> +            | [] -> apply (Terms ((replace a b t)::tail))
Получается. Но что с этим делать? Если только в начале пройтись по всему дереву и сделать везде уникальные имена. Вот только какие имена делать, и как вообще потом ответ смотреть. Там же всё что угодно после переименования будет. Всё же хочется (мб и зря), чтобы имена исходные остались.

2018-03-10 18:37 UTC, uncerso commented on hw.tex
> +$\lambda$z.$\lambda$y.z (K z) = $\lambda$z.z = I
Упс. Воистину. Ну, полагаю, можно не править.

2018-03-10 18:42 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +            | [] -> apply (Terms ((replace a b t)::tail))
Так из-за этого и страдала куча математиков 20-го века, и есть три способа решения проблемы --- соглашение Барендрегта, индексы де Брауна и способ, который я  показывал на паре --- переименование прямо перед подстановкой. Сделать везде уникальные имена (то есть реализовать метод Барендрегта) не поможет, потому что при подстановке переменные могут раскопироваться и перестать быть уникальными --- надо после каждой подстановки снова переименовывать. Я бы тут ожидал увидеть проверку на связанность и переименование до подстановки, это, наверное, проще всего. Можно даже придумать какую-то хитрую логику переименования, которая помогла бы выражению выглядеть прилично после упрощения (например, пройтись по ответу и переименовать переменные снова в x, y, z и т.д. в порядке вхождения)

2018-03-10 18:42 UTC, yurii-litvinov commented on hw.tex
> +$\lambda$z.$\lambda$y.z (K z) = $\lambda$z.z = I
Ага

2018-03-13 20:57 UTC, uncerso commented on FirstSteps/FirstSteps/Program4.fs
> +            | [] -> apply (Terms ((replace a b t)::tail))
А изначально может быть случай
λx.(λx. x) x ? (Желательно, чтоб нет.)
И могут ли быть названия переменных числами.toString() от, скажем, 1e15? Т.е. понятно, что могут, но можно их занять для удобства?

2018-03-13 21:54 UTC, uncerso commented on FirstSteps/FirstSteps/Program4.fs
> +            | [] -> apply (Terms ((replace a b t)::tail))
О, и, полагаю, если свободные переменные не будут равны ни одной из связанных, то тогда можно же ренеймом в самом начале обойтись? Дальше коллизий быть не должно.

2018-03-22 06:38 UTC, yurii-litvinov requested changes
Write-only-код получился. Наверное, оно работает, но из кода это совершенно неочевидно

2018-03-22 06:38 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +    let nextIntNumber = ref 0UL//1000000000000000UL
Не, ref-ячейки всё ещё запрещены, в этой домашке писать в императивном стиле нельзя

2018-03-22 06:38 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +            | o ->Terms <| (List.foldBack (fun el acc -> (apply el) ::acc) (o::tail) [])
Что-то у Вас пробелы перед `::` то есть, то нету

2018-03-22 06:38 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +    let rec foo (ls:list<int>) x =
зшбс :)

2018-03-22 06:38 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +        else 0::newStr
И я так и не понял, что она делает. Немного рефакторинга и переименований бы не помешало.

2018-03-22 06:38 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +    | :? list<int> as ls -> List.fold (fun s c -> s+string(char(c + int('a')))) "" ls
Что-то пробелов не хватает

2018-03-22 06:38 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +            | Var(x) -> if (Map.containsKey x mp) then Var (Map.find x mp)
tm, mp, ... Что за олимпиадство? :)

2018-03-22 18:23 UTC, uncerso commented
Ещё как-то сложновато писать понятный сложный код, используя буквально только рекурсию и match.

2018-03-26 17:13 UTC, yurii-litvinov reviewed
В общем, 4.3 я бы, пожалуй, зачёл. Попытка сделать хорошо привела к тому, что оказалось сложно :) Но работает, ну и с точки зрения пользователя выглядит лучше, чем типовое решение.

2018-03-26 17:13 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +//returns next element in the sequence: a, b, .. z, aa, ab, .. az, ba, bb, ...  (a..z are represented as 0..25)
Я думаю, было бы более естественно представлять символы 'a'..'z' ... символами 'a'..'z', по крайней мере, в результирующем списке. И написано, что оно возвращает следующий элемент, но на самом деле оно возвращает список (и название тоже об этом свидетельствует). Если хочется сгенерировать последовательность a, b, ... z, aa, ..., az, aaa, ..., то, может, имеет смысл это делать как раз через последовательность, через seq и yield, и тогда уже честно забирать следующий элемент. Мм, не как список букв, а как честную строку.

2018-03-26 17:13 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +        let (newStr,newCarry) = add ls 1
Пробела после запятой не хватает :)

2018-03-26 17:13 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +            let rec selectNextName occupiedNames name =
Что-то не то с отступами

2018-03-26 17:13 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +                let newName = next(name)
Это ж аппликация, скобки не нужны

2018-03-26 17:13 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +                        (Var newVar, name, if(needUpdateOccupiedNames) then Set.add newVar occupiedNames else occupiedNames)
Получается, что rename --- это функция, принимающая 6 аргументов и возвращающая 3. Неплохо :) То есть, плохо, конечно :) Можно было бы сделать что-нить вроде структуры Context, куда положить мапу переименований, множество занятых имён и способ получения следующего имени, тогда эта штука принимала бы терм и контекст, и возвращала бы альфа-преобразованный терм и новый контекст. По сути то же самое, но, поскольку у Context поля были бы именованные, в коде было бы более ясно объяснено, что тут происходит.

2018-03-26 17:13 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program4.fs
> +        let rec replace a b tm =
Не "a", "b", а "кого", "во что" :)

2018-03-31 14:37 UTC, yurii-litvinov requested changes

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +let checkBranches ls =
Brackets?

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +                | '(' -> if (x = ')') then tail else t::res
Можно было сделать маленькую однострочную функцию и стало бы немножко меньше копипаста. Впрочем, это можно не править, и так ок

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +    List.map << (*)
В условии просили написать шаги вывода

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +    let ls = ref []
Тут ещё нельзя было ref-ы

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/XUnitTest/Tests2.fs
> +    checkBranches ('['::']'::'['::']'::'['::']'::[]) |> should be True
Оу. Хотелось бы, чтобы функция принимала строку

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/XUnitTest/Tests2.fs
> +    func 10 (1::2::3::4::5::[]) |> should equal <| 10::20::30::40::50::[]
По условию требовалось проверить эквивалентность функций с помощью FsCheck

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/XUnitTest/Tests2.fs
> +//=======================</task3>======================
А ещё нужны тесты на бизнес-логику телефонного справочника

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +let printTextAndReadStringAnswer text =
Принцип единственности ответственности расстроен. Хотя можно было бы переименовать просто в getInput, например, а text переименовать в prompt --- тогда бы функция делала что-то одно: получала бы от пользователя ввод, выводя в процессе подсказку

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +let add ls =
Надо пустую строку сежду функциями

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +    find number ls
Что-то копипаст...

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +    | x::tail -> printfn "%s : %s" <| fst x <| snd x; print tail
Принято по одному оператору на строку

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +        | s::tail -> fout.WriteLine((fst s) + " " + (snd s)); print fout tail
И тут. Лучше `;` вообще избегать

2018-03-31 14:37 UTC, yurii-litvinov commented on FirstSteps/FirstSteps/Program5.fs
> +    if (File.Exists(path) = false)
`not <| File.Exists(path)`?

2018-04-03 07:03 UTC, yurii-litvinov commented
Мне кажется, пришла пора создать новую ветку от мастера и новый пуллреквест

2018-04-03 07:14 UTC, uncerso commented
Вечерком.

2018-04-03 07:48 UTC, uncerso commented
Ок. Тогда сюда новые задачи больше не пойдут. Но те, что вы ещё не одобрили, вероятно, имеет смысл тут и добить.

2018-04-19 20:01 UTC, merged